
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { expand } from "dotenv-expand";
expand(dotenv.config({ path: ".env.local" }));
expand(dotenv.config()); // fallback to .env
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Use direct connection for migrations (not pooled)
    url: env("DIRECT_URL"),
  },
});
